### ISSUE TITLE
ros环境运行出错

### ISSUE THREAD

**Issue by woshidag** [percipioxyz/camport_linux#1]
使用最新版本的libcamm.so （x64版本）。出错了，错误如下
已经是第二次了，麻烦下次测试下ros环境喂。

运行：roslaunch openni2_launch openni2.launch 
[ INFO] [1481094267.688659274]: Initializing nodelet with 4 worker threads.
Percipio camera number 1
[ INFO] [1481094267.802308032]: Device "1" found.
[FATAL] [1481094268.395191212]: Failed to load nodelet '/camera/points_xyzrgb_sw_registered` of type `depth_image_proc/point_cloud_xyzrgb` to manager `camera_nodelet_manager'
[FATAL] [1481094268.395265264]: Failed to load nodelet '/camera/driver` of type `openni2_camera/OpenNI2DriverNodelet` to manager `camera_nodelet_manager'
[FATAL] [1481094268.395332267]: Failed to load nodelet '/camera/depth_points` of type `depth_image_proc/point_cloud_xyz` to manager `camera_nodelet_manager'
[FATAL] [1481094268.395456346]: Failed to load nodelet '/camera/depth_metric` of type `depth_image_proc/convert_metric` to manager `camera_nodelet_manager'
[FATAL] [1481094268.395881409]: Failed to load nodelet '/camera/rgb_rectify_color` of type `image_proc/rectify` to manager `camera_nodelet_manager'
[FATAL] [1481094268.396469854]: Failed to load nodelet '/camera/depth_rectify_depth` of type `image_proc/rectify` to manager `camera_nodelet_manager'
[FATAL] [1481094268.396682385]: Failed to load nodelet '/camera/register_depth_rgb` of type `depth_image_proc/register` to manager `camera_nodelet_manager'
[FATAL] [1481094268.396889380]: Failed to load nodelet '/camera/depth_metric_rect` of type `depth_image_proc/convert_metric` to manager `camera_nodelet_manager'

运行老版本的则正常
Percipio camera number 1
[ INFO] [1481094349.246644077]: Device "1" found.
   517901 VERBOSE    no processor for this packet
   518157 VERBOSE    no processor for this packet
   518372 VERBOSE    no processor for this packet
   518676 VERBOSE    no processor for this packet
   525672 VERBOSE    deviceparam packet accepted
   525750 INFO       waiting device...
   525789 VERBOSE    no processor for this packet
   634396 VERBOSE    deviceparam packet accepted
   634522 INFO       no custom config data
   634558 VERBOSE    no processor for this packet
   743426 VERBOSE    deviceparam packet accepted
   743579 VERBOSE    no processor for this packet
   852069 VERBOSE    deviceparam packet accepted
   852362 VERBOSE    no processor for this packet
  1037223 VERBOSE    deviceparam packet accepted
PercipioDriver: success to open device!
[ERROR] [1481094349.879047330]: Unsupported IR video mode - Resolution: 640x480@30Hz Format: Gray16
[ERROR] [1481094349.879358940]: Unsupported color video mode - Resolution: 640x480@30Hz Format: RGB888

**Comment by percipioxyz** [comment]
使用的是新版本的linux camport 驱动吧，请同步更新openni2的软件包，这两个软件包之间有依赖关系：）

**Comment by percipioxyz** [comment]
问题是否解决了？

**Comment by woshidag** [comment]
已经解决。都更新到最新版本。谢谢
