### ISSUE TITLE
open device failed

### ISSUE THREAD

**Issue by xxsong5** [percipioxyz/camport_linux#2]
./camtest 
camport api version is 4
open device failed

**Comment by percipioxyz** [comment]
请问使用的设备是哪一个型号？
USB接口是否有接触不良，拔插一下看看USB设备是否枚举正常？

**Comment by percipioxyz** [comment]
另请注意设备的访问需要root权限，请尝试使用sudo ./camtest, 谢谢

**Comment by xxsong5** [comment]
yes,  sudo is right, thanks!,
